import type { Config } from 'tailwindcss'

export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#4f378a',
        'inverse-on-surface': '#f5eff7',
        'error': '#ba1a1a',
        'surface-container-low': '#f8f2fa',
        'on-primary-container': '#e0d2ff',
        'on-primary': '#ffffff',
        'surface-dim': '#ded8e0',
        'inverse-primary': '#cfbcff',
        'surface-container-highest': '#e6e0e9',
        'on-tertiary-fixed': '#241a00',
        'outline': '#7a7582',
        'tertiary': '#765b00',
        'primary-fixed-dim': '#cfbcff',
        'on-tertiary-fixed-variant': '#594400',
        'on-tertiary-container': '#503d00',
        'secondary-fixed-dim': '#cdc0e9',
        'primary': '#4f378a',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#e7c365',
        'on-primary-fixed': '#22005d',
        'inverse-surface': '#322f35',
        'on-secondary-container': '#645a7d',
        'surface-bright': '#fdf7ff',
        'secondary-fixed': '#e9ddff',
        'on-secondary-fixed': '#1f1635',
        'background': '#fdf7ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#ffdf93',
        'on-tertiary': '#ffffff',
        'on-surface': '#1d1b20',
        'on-error': '#ffffff',
        'secondary-container': '#e1d4fd',
        'tertiary-container': '#c9a74d',
        'primary-fixed': '#e9ddff',
        'surface-container': '#f2ecf4',
        'on-background': '#1d1b20',
        'on-error-container': '#93000a',
        'surface-container-high': '#ece6ee',
        'outline-variant': '#cbc4d2',
        'secondary': '#63597c',
        'on-secondary-fixed-variant': '#4b4263',
        'surface': '#fdf7ff',
        'on-surface-variant': '#494551',
        'surface-tint': '#6750a4',
        'primary-container': '#6750a4',
        'surface-variant': '#e6e0e9',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'md': '24px',
        'base': '4px',
        'xl': '80px',
        'xs': '8px',
        'sm': '16px',
        'lg': '48px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'h3': ['Plus Jakarta Sans', 'sans-serif'],
        'h2': ['Plus Jakarta Sans', 'sans-serif'],
        'label-hand': ['Be Vietnam Pro', 'sans-serif'],
        'h1': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'h3': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'h2': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'label-hand': ['14px', { lineHeight: '1.2', fontWeight: '500' }],
        'h1': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        'sketch': '4px 4px 0px 0px rgba(44, 44, 44, 1)',
        'sketch-sm': '2px 2px 0px 0px rgba(44, 44, 44, 1)',
        'sketch-lg': '8px 8px 0px 0px rgba(44, 44, 44, 1)',
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0px 0px 20px rgba(255, 179, 71, 0.4)' },
          '50%': { boxShadow: '0px 0px 40px rgba(255, 179, 71, 0.8)' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config
